# custom_exception_python